# Generated by Django 4.0 on 2022-01-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('shortname', models.CharField(max_length=20, verbose_name='Nombre corto')),
                ('anulate', models.BooleanField(default=False, verbose_name='anulado')),
            ],
        ),
    ]
