# Generated by Django 4.0 on 2022-01-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='shortname',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nombre corto'),
        ),
    ]
