# Generated by Django 4.0 on 2022-01-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='subtitulo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
