# Generated by Django 4.0 on 2022-01-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HABILIDAD', models.CharField(max_length=20, verbose_name='Habilidades')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades empleados',
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['firstname'], 'verbose_name': 'Personas', 'verbose_name_plural': 'Mis empleados'},
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('firstname', 'lastname')},
        ),
    ]
