# Generated by Django 4.0 on 2022-01-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_habilidades_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidades', 'verbose_name_plural': 'Habilidades empleados'},
        ),
        migrations.RenameField(
            model_name='habilidades',
            old_name='HABILIDAD',
            new_name='habilidad',
        ),
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='persona.Habilidades'),
        ),
    ]
