# Generated by Django 4.0 on 2022-01-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_remove_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre Completo'),
        ),
    ]
